# Generated by Django 3.2.7 on 2021-11-18 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_order', to='orders.order'),
            preserve_default=False,
        ),
    ]
