# Generated by Django 3.2.7 on 2021-11-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='state',
        ),
    ]
