# Generated by Django 3.2.7 on 2021-11-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_city_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
