# Generated by Django 3.2.7 on 2021-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
